[env:marble]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = groundstudio_marble_pico
framework = arduino

board_build.core = earlephilhower
board_build.f_cpu = 133000000L
board_build.usb_mode = pico_sdk

monitor_speed = 115200

build_flags =
  -Wall
  -Wextra
  -std=gnu++17
  -I src/Core/Models
  -I src/Core/Services
  -I src/Presentation
  -I src/Drivers
  -I src/Fonts

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3

; --- SCHIMBAT ---
upload_protocol = picotool
;upload_port = *