[platformio]
default_envs = marble

[env:marble]
# CORECTAT: Link-ul oficial complet pentru platforma extinsă RP2040
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

; Arduino-Pico (Earle Philhower)
board_build.core = earlephilhower

; Hardware specificații tehnice fizice
board_build.f_cpu = 133000000L
board_upload.flash_size = 8388608
board_build.usb_mode = pico_sdk
monitor_speed = 115200

; INJECTARE RUTE GLOBALE DIRECTE
build_flags =
    -Wall
    -Wextra
    -std=gnu++17
    -I src/Core/Models
    -I src/Core/Services
    -I src/Presentation
    -I src/Drivers
    -I src/Fonts

; Managementul automatizat al bibliotecilor grafice
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3

; CONFIGURARE AUTOMATĂ COMPLETĂ (Ocolește literele rigide de tip D:\, E:\)
upload_protocol = mbed
upload_port = *    

