[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

monitor_speed = 115200

lib_deps =
    olikraus/U8g2 @ ^2.36.15

build_flags =
    -Wall
    -Wextra
    -std=gnu++17
