[platformio]
default_envs = marble_pico


[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200

build_flags =
    -Wall
    -Wextra
    -std=gnu++17
    -I src/Core/Models
    -I src/Core/Services
    -I src/Presentation
    -I src/Drivers
    -I Fonts

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.6 ;@ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0 ;@ ^1.10.3
    adafruit/Adafruit ILI9341@^1.6.3
    paulstoffregen/XPT2046_Touchscreen ; @ ^1.0.7 
    circuitstate/CSE_CST328@^0.0.5
upload_port = auto
upload_protocol = custom
upload_command = powershell -NoProfile -ExecutionPolicy Bypass -File scripts\upload_pico.ps1 -FirmwarePath "$BUILD_DIR\firmware.uf2" -UploadPort "$UPLOAD_PORT"


; ============================================================
; MARBLE PICO
; ============================================================

[env:marble_pico]

board = groundstudio_marble_pico

board_build.f_cpu = 133000000L
board_build.usb_mode = pico_sdk

build_flags =
    ${env.build_flags}
    -D SERVICEBOX_MARBLE


; ============================================================
; WAVESHARE RP2350 TOUCH LCD 2.8
; ============================================================

[env:waveshare_rp2350]

board = rpipico2

build_flags =
    ${env.build_flags}
    -D SERVICEBOX_WAVESHARE


